using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Naratteu.Anonymous;

/// <summary>진입점 이름과, 이 컴파일이 C#14 확장 멤버를 받아주는지 여부.</summary>
sealed record Opts(string Entry, string Holder, bool Extensions);

static class Emitter
{
    public static void Emit(SourceProductionContext spc, ImmutableArray<Candidate> all, Opts names)
    {
        var mine = all.Where(c => c.InvokedName == names.Entry).ToList();
        foreach (var d in mine.SelectMany(c => c.Diagnostics))
            spc.ReportDiagnostic(d.ToDiagnostic());

        Dictionary<string, AnonTarget> targets = [];
        foreach (var c in mine)
            if (c.Target is { } t) targets[t.DefKey] = t;
        if (targets.Count is 0) return;

        // ===== 상속 체이닝: 파생 인터페이스의 구현클래스가 상위 구현클래스를 상속하게 해서
        //       제네릭 형태 호출의 오버로드 모호성을 없앤다.
        Dictionary<string, BaseRef> chain = [];
        Dictionary<string, HashSet<string>> visible = [];
        Dictionary<string, List<AnonMember>> emitted = [];

        foreach (var t in targets.Values.OrderBy(t => t.Bases.Count))
        {
            var cands = t.Bases.Where(b => targets.ContainsKey(b.DefKey)).ToList();
            BaseRef? pick = cands.FirstOrDefault(b =>
                cands.All(o => o.DefKey == b.DefKey || targets[b.DefKey].Bases.Any(x => x.DefKey == o.DefKey)));

            var members = t.Members.Items.ToList();
            if (pick is { } p)
            {
                var covered = Covered(targets[p.DefKey]);
                var trimmed = members.Where(m => !covered.Contains(m.DeclKey)).ToList();
                if (trimmed.Any(m => m.TypeRef is not null && visible[p.DefKey].Contains(m.Name)))
                    pick = null;                       // 이름이 겹치면 체이닝 포기하고 평평하게 다 구현
                else
                    members = trimmed;
            }

            if (pick is { } ok) chain[t.DefKey] = ok;
            emitted[t.DefKey] = members;
            visible[t.DefKey] = [
                .. members.Where(m => m.TypeRef is not null).Select(m => m.Name),
                .. pick is { } q ? visible[q.DefKey] : [],
            ];
        }

        foreach (var t in targets.Values)
            spc.AddSource($"{t.ImplName}.g.cs", Source(ImplClass(t, emitted[t.DefKey], chain.TryGetValue(t.DefKey, out var b) ? targets[b.DefKey].ImplRef(b.TypeArgs) : null)));

        spc.AddSource("Anonymous.Entry.g.cs", Source(Entry(targets, mine, names)));

        if (!names.Extensions)
            foreach (var c in mine.Where(c => c is { GenericForm: false, Target: not null }))
                spc.ReportDiagnostic(Diagnostic.Create(Diags.ExtensionNeedsCSharp14, c.At?.ToLocation(), c.ConstructedRef, names.Holder, names.Entry));

        // ===== 제네릭 형태가 상속관계 때문에 모호해지는 경우 알려준다
        foreach (var c in mine.Where(c => c is { GenericForm: true, Target: not null }))
            if (targets.Values.Any(d => d.DefKey != c.Target!.DefKey
                                     && d.Bases.Any(x => x.DefKey == c.Target.DefKey)
                                     && !ChainsTo(d, c.Target.DefKey)))
                spc.ReportDiagnostic(Diagnostic.Create(Diags.AmbiguousGenericForm, c.At?.ToLocation(), c.ConstructedRef));

        bool ChainsTo(AnonTarget from, string key)
        {
            for (var cur = from; chain.TryGetValue(cur.DefKey, out var up); cur = targets[up.DefKey])
                if (up.DefKey == key) return true;
            return false;
        }
    }

    /// <summary>object 의 멤버를 가리는 이름이면 new 를 붙여줘야 CS0108 이 안 샌다. (IEqualityComparer 의 Equals 같은 것)</summary>
    static bool Hides(string name) => name is "Equals" or "GetHashCode" or "ToString" or "GetType" or "MemberwiseClone" or "Finalize";

    static HashSet<string> Covered(AnonTarget t) => [t.DefKey, .. t.Bases.Select(b => b.DefKey)];

    static SourceText Source(string text) => SourceText.From(text, Encoding.UTF8);

    static string ImplClass(AnonTarget t, List<AnonMember> members, string? baseRef)
    {
        List<string> body = [
            .. members.Select(m => m.DelegateDecl).Where(d => d is not null).Select(d => d!),
            .. members.Select(m => m.ExplicitImpl).Where(i => i is not ""),
        ];
        var props = members.Where(m => m.TypeRef is not null)
            .Select(m => $"public {(Hides(m.Name) ? "new " : "")}{(m.Required ? "required " : "")}{m.TypeRef} {m.Name} {{ get; init; }}{(m.Initializer is null ? "" : $" = {m.Initializer};")}")
            .ToList();
        if (body.Count > 0 && props.Count > 0) body.Add("");
        body.AddRange(props);

        return $$"""
            // <auto-generated/>
            #nullable enable
            namespace Naratteu.Anonymous.Generated
            {
                internal class {{t.ImplName}}{{t.TypeParams}} : {{(baseRef is null ? "" : baseRef + ", ")}}{{t.DefKey}}{{(t.Constraints is "" ? "" : " " + t.Constraints)}}
                {
            {{body.Select(l => l is "" ? "" : $"        {l}").Join("\n")}}
                }
            }
            """;
    }

    static string Entry(Dictionary<string, AnonTarget> targets, List<Candidate> mine, Opts names) => $$"""
        // <auto-generated/>
        #nullable enable

        /// <summary>제네릭 형태: {{names.Holder}}.{{names.Entry}}&lt;IFoo&gt;(new() { .. })</summary>
        internal static class {{names.Holder}}
        {
        {{mine.Where(c => c.Target is not null).GroupBy(c => c.ConstructedRef).Select(g => g.First())
              .Select(c => $"    public static {c.ConstructedRef} {names.Entry}<A>({targets[c.Target!.DefKey].ImplRef(c.TypeArgs)} impl) where A : {c.ConstructedRef} => impl;").Join("\n")}}
        }

        {{(names.Extensions ? $$"""
        /// <summary>확장 형태: IFoo.{{names.Entry}}(new() { .. })</summary>
        internal static class {{names.Holder}}Extensions
        {
        {{targets.Values.Select(t => $$"""
            extension{{t.TypeParams}}({{t.DefKey}}){{(t.Constraints is "" ? "" : " " + t.Constraints)}}
            {
                public static {{t.DefKey}} {{names.Entry}}({{t.ImplRef(t.TypeParams)}} impl) => impl;
            }
        """).Join("\n")}}
        }
        """ : "// 확장 형태는 C# 14 부터라 이 컴파일에선 만들지 않는다")}}
        """;
}
