namespace Naratteu.Anonymous;

/// <summary>소비측 컴파일에 항상 심어주는 런타임 타입들. 별도 참조 없이 쓰라고 소스로 넣는다.</summary>
static class RuntimeSource
{
    public const string Text = """
        // <auto-generated/>
        #nullable enable
        namespace Naratteu.Anonymous
        {
            /// <summary>읽기전용 프로퍼티. 값을 그대로 주거나 new() { get = () => .. } 로 게터를 준다.</summary>
            internal sealed class Get<T>
            {
                public required global::System.Func<T> get { get; init; }
                public T Value => this.get();
                public static implicit operator Get<T>(T value) => new() { get = () => value };
            }

            /// <summary>쓰기전용 프로퍼티. new() { set = v => .. } 로 세터를 준다.</summary>
            internal sealed class Set<T>
            {
                public required global::System.Action<T> set { get; init; }
                public T Value { set => this.set(value); }
            }

            /// <summary>읽고쓰는 프로퍼티. 값을 그대로 주면 자동 저장소가 붙고, new() { get = .., set = .. } 로 접근자를 직접 줄 수도 있다.</summary>
            internal sealed class Prop<T>
            {
                public required global::System.Func<T> get { get; init; }
                public required global::System.Action<T> set { get; init; }
                public T Value { get => this.get(); set => this.set(value); }
                public static implicit operator Prop<T>(T value)
                {
                    var box = value;
                    return new() { get = () => box, set = v => box = v };
                }
            }

            /// <summary>이벤트. 아무것도 안 주면 보통의 자동구현 이벤트처럼 굴러가고, Handler 로 꺼내 호출할 수 있다.</summary>
            internal sealed class Ev<T> where T : global::System.Delegate
            {
                private T? _handler;
                public global::System.Action<T?>? add { get; init; }
                public global::System.Action<T?>? remove { get; init; }
                public T? Handler => _handler;
                public void Add(T? value) { if (this.add is { } a) a(value); else _handler = (T?)global::System.Delegate.Combine(_handler, value); }
                public void Remove(T? value) { if (this.remove is { } r) r(value); else _handler = (T?)global::System.Delegate.Remove(_handler, value); }
            }
        }
        """;
}
